In [77]:
import numpy as np

In [158]:
stations_arr = np.array([0.0, 87.0, 174.0, 261.0, 348.0])
stations_arr

array([  0.,  87., 174., 261., 348.])

In [165]:
self_loc = 88
drive_distance_max = 20

In [166]:
station_dist_arr = self_loc + drive_distance_max - stations_arr
station_dist_arr

array([ 108.,   21.,  -66., -153., -240.])

In [167]:
station_dist_arr[stations_arr < self_loc] = np.inf # only ahead of current position
station_dist_arr

array([  inf,   inf,  -66., -153., -240.])

In [168]:
station_dist_arr[station_dist_arr < 0] = np.inf # only reachable
station_dist_arr

array([inf, inf, inf, inf, inf])

In [169]:
stations_arr[np.argmin(station_dist_arr)]

0.0

Driver: 2 289.34559221200647 [[  0.  87. 174. 261. 348.]] [[289.34559221 202.34559221 115.34559221  28.34559221   0.        ]]
Driver: 3 212.41631162507608 [[  0.  87. 174. 261. 348.]] [[212.41631163 125.41631163  38.41631163   0.           0.        ]]

In [128]:
print(station_dist_arr, np.nonzero(station_dist_arr))

[289.34559221 202.34559221 115.34559221  28.34559221   0.        ] (array([0, 1, 2, 3]),)


In [ ]:
# go to smallest that is > 0
# but only to the ones ahead of current position.

In [30]:
station_dist_arr[2]

2

In [33]:
station_dist_arr[station_dist_arr < 0] = 0
station_dist_arr

array([22, 12,  2,  0,  0])